### ISSUE TITLE
IMPROVEMENT: Arcade-card game detection

### ISSUE THREAD

**Issue by SwedishGojira** [MiSTer-devel/TurboGrafx16_MiSTer#107]
Would it be possible to make the core detect a dummy-file named "arcade-card.rom" in the rom folder (similar to what you have done for per-game bios loading) and automatically activate the arcade-card setting?

**Comment by dshadoff** [comment]
What's the point of this ?  You can turn it on or off from the OSD; your suggestion would override that, potentially causing confusion for debug.

**Comment by SwedishGojira** [comment]
This would automate the action for those games that need it. The way it is now you have to remember to "flip the switch" for the games that need the arcade-card to work every time you want to play them. Since all games have their own separate folder it is easier to just put a dummy file in there to have the core activate it automatically.

If this could be automated by reading the filename similar to what some other cores do (SMS if I remember correctly) to set "arcade card mode" if it finds "(Arcade card)" in the filename it is loading this would work nice as well.

The way it is now alot of people think their games are not working properly or that they have hit a bug of the core because they jut forget to flip the switch manually.

**Comment by Left-Empty** [comment]
I'm unsure what games you are thinking about, as I have had zero issues with games playing improperly because of the Arcade Card, in the same way I have had zero such issues on the real hardware. I don't play all games, though!

To my own knowledge, the only games that would benefit from such an option are hybrid games, if you wish to disable the Arcade Card features (usually simply limited to using CD tracks over the internal PSG for cutscenes and such); but then, flipping the switch and resetting the machine is even easier than taking the Arcade Card out of a real system.

As someone who prefer the PSG soundtracks as well as shorter loadings and don't play any Arcade Card-only games, I confess egotistically to disabling the setting overall.

**Comment by dshadoff** [comment]
I think this request may be founded on a misunderstanding.
You can just set Arcade Card support to always on, and it will always be there when needed.  This is equivalent to leaving an "Arcade Card" plugged into the PC Engine, instead of just a "Super System Card".

The Arcade Card will not be active when playing .PCE or .SGX games, so there is no interference there.

The only possible downside would be that you need to switch it off if you deliberately wanted to see:
a) A warning message for an Arcade Card game ("need arcade Card")
or
b) A SCD/ACD dual-compatible game run in SCD-only mode.  But in truth, the differences aren't so big, and the Arcade Card support enhances the game.

This might help to explain my initial confusion at the request.

**Comment by sorgelig** [comment]
There is no evidence that arcade card gives problem for some games. There was a bug in the core enabled CD system for non-CD games. It was fixed already.

If you will find a game having issue with arcade card, then feel free to open an another issue.

**Comment by SwedishGojira** [comment]
OK. Misunderstanding from my side then based on wrongful info from other sources. Sorry guys. I will just set it to on by standard. Keep up the good work and thank you from your hard work on this core and MiSTer in general. You saved me from buying an expensive PC Engine, just so you know ;)
