### ISSUE TITLE
[HUCARD] Rock-On (Japan) - Remains sprites during the intro from previous game or after a reset of this game

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/TurboGrafx16_MiSTer#109]
Hi,
I tried this game Rock-On (Japan) (with this sha1sum 19a7744bc8355076f481446978f49175dbd132b9  Rock-On (Japan).pce)

If you come from a previous game or reset this game, you will find remains sprites from the previous games during the intro.

**Comment by dshadoff** [comment]
This is due to the game not clearing video RAM at startup, yet enabling (uninitialized) sprites.

You can also see this if you have a TurboEverdrive; play a game or a demo with an obvious sprite (for example, Chris Covell's SplitRes demo, when the ball is in the top left corner), and press the button on the Everdrive to return to menu.  Then play RockOn.

This can be corrected by initializing video RAM at the time of "new game load", but I think this is not appropriate for "warm reset" - certain other games may rely on the stored values.

**Comment by wwark** [comment]
Hi @dshadoff,
Thank you for your explanation and the check on the real hardware.

**Comment by dshadoff** [comment]
Sorgelig has implemented a video RAM clear to cover your scenario; it will be available in the next release.
