### ISSUE TITLE
Saving not working on Downtown Nekketsu Monogatari

### ISSUE THREAD

**Issue by joshuaryoung** [MiSTer-devel/TurboGrafx16_MiSTer#122]
PC Engine CD release won’t save progress. I’ve tried manually saving / loading, using autosave and “format backup ram” and nothing fixes the problem.

**Comment by dshadoff** [comment]
Are you reporting this against the September release of the core ?  If so, have you tried to confirm whether the previous release has the same behavior or not ?

**Comment by dshadoff** [comment]
Also, were you successful with saving on any other games ?  (If so, which one(s) ?)

**Comment by dshadoff** [comment]
I just tested this function of this game on the most recent core and it works fine for me.

Note that in-game you need to press RUN to get an auxiliary functions menu, for which you need to choose the save function under the load/save choice "ロード/セーブ" and then save - as step 1.
Step 2 is that (and this is true for other cores as well), you need to go to the OSD menu even if auto-save is active.  In my case, I leave auto-save off, and explicitly save from the OSD menu.

I'm not sure if you were doing all of this.

**Comment by joshuaryoung** [comment]
- most recent core (20200922.rbf)
- just tried the steps you outlined (セーブ-> OSD “Save Backup RAM”)
- tried manually loading from osd
- Rondo of Blood saves just fine 

Still not saving...

**Comment by dshadoff** [comment]
OK, break this into two steps - saving and loading.
1) For save, walk through the steps above - in-game menu to save, followed by OSD save.
-> Two things I'd like to confirm:
a) Does a file get created on the SDCard (or elsewhere if you are using USB storage) in : saves/TGFX16/* with the filename of the image/cue ?  If so, please place a copy of it in your reply.
b) If not, please show a directory of saves/TGFX16/* , and also put the name of the Downtown Nekketsu image/cue here.

2) For load, when you start the game, the save file should be loaded automatically when you start the game.  At the CDROM boot screen, instead of pressing RUN, press SELECT, and choose the top choice.  Take a screenshot of what is displayed there.  Three items should be displayed.  Don't select any of them; press the USER button on the MiSTer and restart the game.

When you start the game, you initially appear back at the starting alley where nothing is going on.  This is the opportunity to load from the save file.  You will again need to go to the auxiliary menu by pressing RUN and choosing ロード/セーブ, this time choosing ロード and selecting which slot to load from.  If successful, your status and location should return to the appropriate saved state.

**Comment by joshuaryoung** [comment]
Fixed it. It must have been a bad rom or a file name problem. Thanks for all the troubleshooting help! Above and beyond!

For anyone reading this in the future: Got a different rom with '_' replacing ' ' in the file name so one of those two things likely fixed it.
