### ISSUE TITLE
Mad Stalker - Full Metal Force (Japan) Corrupted Sprites

### ISSUE THREAD

**Issue by blisstik** [MiSTer-devel/TurboGrafx16_MiSTer#164]
Using the latest core with Shadow Mask support, I had to enable card support to boot the game. It works but the main character has corrupted sprite animation.

**Comment by dshadoff** [comment]
Mad Stalker is an Arcade Card game and requires Arcade Card to be enabled.
I updated to the latest core, and I did not see the corruption you describe.

Did you run the game with any special options/play modes ?  Or just the default start by pressing run directly ?
Did you play this game on previous versions of the core without corruption, or is this the first time you are playing it ?

I'm not sure whether you are doing something differently than I am, in order to find an issue that I don't see... but my initial suspicion is that you may have a bad game image.

**Comment by blisstik** [comment]
For some reason, it no longer happens.
