### ISSUE TITLE
Lords of thunder growl sound

### ISSUE THREAD

**Issue by tonysvo614** [MiSTer-devel/TurboGrafx16_MiSTer#175]
Turbo graf x cd in this game sometimes growl and not when killing enemies.

**Comment by dshadoff** [comment]
Could you provide an example of what you are describing ?
Specifically, an example of what you think is wrong, and an example of what you think is correct.
Ideally, the 'correct' would be an example from original hardware.

Otherwise, I have no idea of what you are talking about.

**Comment by tonysvo614** [comment]
For instance 1st level where you destroy the dragon with head moving back and forth. After the 2nd creature that comes out of ground. it should make a growl when being killed it does this 1 out of 10 times. Another example is the creature that spins and has spikes should as well.

**Comment by dshadoff** [comment]
I suppose that you're referring to the dragon-thing on world "Dezant" (default), while using the "Fire Armor" (default) ?
This works for me, every time.

I believe that you're either:
a) Using the hack image of the game with remixed audio (louder CD music), or
b) Have your settings set to "CD Audio Boost = Yes".

...in which case, the sound may be drowned out by the CD audio.
Make sure that your CD Audio Boost setting is set to "No", and use the correct image.

I've also found that "ADPCM Boost = Yes" can help, as certain frequencies of ADPCM (voices in particular) seem to need a bit of exaggeration on this core, in order to compete with CD audio and the PSG sound.

If you think I may have misunderstood, please post a video of where you think it isn't acting properly, including the steps that you took to get there (for example, there are 6 possible worlds where this game can be started....)

**Comment by tonysvo614** [comment]
Ok i found the problem ...if you have custom filter on in the settings no growls will be heard needs to be set to internal filter.
