### ISSUE TITLE
6 Button Controller issue

### ISSUE THREAD

**Issue by snakeX79** [MiSTer-devel/TurboGrafx16_MiSTer#191]
When I set Comtroller to 6 buttons There are slower movements in directions. For example Shinobi I can't to move. Shinobi is flashing fast.

**Comment by dshadoff** [comment]
Not a bug.
Very few games supported 6-button controls, and this game was not one that did. All 6-button controllers had a switch to revert to 2-button mode for regular games. Use 2-button mode.

Please close.

**Comment by snakeX79** [comment]
For example Shinobi needs 3 buttons so its not fully playable.

**Comment by dshadoff** [comment]
I don't know which version of the game you are thinking about, but this bug is filed against the PC Engine core.
The PC Engine version of Shinobi was published in 1989 for a 2-button controller (as shown on page 5 of the manual).  The 6-button controller wasn't even released until 1993.

The 3-button PC Engine controller (where button 3 is just another instance of the RUN button, used for Forgotten Worlds for example), also wasn't released until 1991.  (And Shinobi doesn't use the RUN button for any in-game moves; it's just a pause.)

Not a bug.  Close.

**Comment by sorgelig** [comment]
Yeah, it's not a bug. Just game is not compatible with 6-button controller.
