### ISSUE TITLE
Moto Roader PC Engine CD 6 button glitch

### ISSUE THREAD

**Issue by wiselinkpro** [MiSTer-devel/TurboGrafx16_MiSTer#214]
When enabling 6 buttons (which is what this game uses in order to fire rockets at opponents), the core behaves as if the down button on the controller is pressed down all the time.

**Comment by dshadoff** [comment]
Are you referring to "Moto Roader MC" on Super CDROM ?
(Moto Roader is the name of a HuCard game).

I can state definitively that among HuCard games, only Street Fighter II supports 6-button controllers.
Among CDROM games, very few support 6-button controllers, and MotoRoader MC is not on my current list.

Since the 6-button controller was released together with Street Fighter II in June 1993, and MotoRoader MC was released in December 1992, it would not support a controller which didn't exist on the market yet.

Having said this, I went to check the manual of my original copy of the game - just to be certain. While it clearly shows how to use the controller, there is no mention of any controllers other than the basic 2-button controller.

![IMG_2928](https://github.com/user-attachments/assets/bf0e1169-afa6-463f-bf61-01fdf3314aae)


If you go into "OPTION", you can assign which item (or no item) to assign to button 1 or button 2.

![IMG_2929](https://github.com/user-attachments/assets/1a61a921-45eb-4e15-80d6-762f5b84b38b)



If you are referring to an arcade board or other console implementation of this game, the controls would be implemented for each system based on the hardware available.


This is not an issue.
Please close.
