### ISSUE TITLE
Background offset and mirroring in Wonder Momo

### ISSUE THREAD

**Issue by jotego** [MiSTer-devel/TurboGrafx16_MiSTer#39]
Wonder Momo shows the background moved down, with the top part of it repeated. See attached images (which may render rotated on your web browser for some reason...)

![IMG_7509](https://user-images.githubusercontent.com/1863036/56324504-4ea1c700-616f-11e9-9a00-ba5645175d1e.jpg)

![IMG_7511](https://user-images.githubusercontent.com/1863036/56324427-18644780-616f-11e9-8fb4-0f89094d996e.jpg)

**Comment by sorgelig** [comment]
This is very well known issue. Game uses 2 interrupts in the frame but doesn't check which one is occurred, so it swaps the reaction. A good example of bad game coding. It relays on exact timings to work correctly.
Welcome to fix.

**Comment by dshadoff** [comment]
It seems that the reason for this is CPU-VRAM wait states, and that they don't match actual hardware.  The title page is interpreting RCR IRQ as VBLANK, and VBLANK IRQ as RCR, simply because they alternate.  The state at time of entry is key, and is related to VRAM write wait states (possibly among other things).  I will look into this timing soon.

**Comment by sqwirral** [comment]
Checking in today's core and this looks to be fixed.

**Comment by dshadoff** [comment]
Please check with new release.  This should be fixed now.

**Comment by sorgelig** [comment]
fixed
