### ISSUE TITLE
Missing first row of pixels

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/TurboGrafx16_MiSTer#80]
Using Overscan or Linearity test pattern in 240p test suite, the first row of pixels is overscanned even with Overscan:Visible.

**Comment by James-F2** [comment]
https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/commit/9ecd43be8faca6df789e903da23913e8b68db3ba

Now one bottom row of pixels is missing.
Does is have to got by 3?

Bonk 3 image for reference.
![Bonk III - Bonk's Big Adventure (USA)-200519-100615](https://user-images.githubusercontent.com/31185814/82295426-6d990b00-99b8-11ea-945d-d5dfdd13fe76.png)
Top two black rows should not be visible (black in most games).
Bottom row pixels should not be missing.

I think 240p is wrong here,, the two top black rows don't have content in 99% of games.
So the commit can be reverted.

@paulb-nl 
What do you suggest?
Most game don't have content in two upper pixel rows, should they be visible?

**Comment by paulb-nl** [comment]
According to the 240p test, the games usually use a different mode which can show only 239 lines instead of 240. You can change the start line at the options menu.

> Vertical resolution: This system outputs either 224 or 240p video. Although capable of displaying all 240 vertical lines games tend to use only 239; probably to gain the CPU time of 4 extra lines during vblank.

>The suite uses the full 240 mode by default, but you can enable the one games use by selecting to start at line 24 instead of 22. This will clip the last line in patterns, but show the real area used by games.

https://github.com/ArtemioUrbina/240pTestSuite/blob/master/240psuite/PCE/help/options.txt

So we need to show the top line which will be empty in most games. 
`TOP_BL_LINES_E` at 18 is best centered with games with results in 1 black line at the top and bottom.

Currently the core shows the full 240 lines instead of 239 when selecting start at line 24 but I believe this should happen in the 6270 so that the grid with white border enabled starts the border 1 line earlier which clips the last red line of the grid. This needs to be confirmed on hardware.

**Comment by James-F2** [comment]
Yes, I've tested with the following:
constant TOP_BL_LINES_E	: integer := **18**;
TOP_BL_LINES <= TOP_BL_LINES_E when RVBL = '1' else TOP_BL_LINES_E+**4**;

Yes, it is great in all resolutions with no missing pixels rows.
Leaving 1 black row at top and bottom in most games.

**Comment by paulb-nl** [comment]
Is `TOP_BL_LINES_E+4` not too low with overscan hidden and 240p start line 24 or 224p?

`TOP_BL_LINES_E+6` seems better centered here.

**Comment by James-F2** [comment]
Will that effect only the Overscan:Hidden option?

**Comment by paulb-nl** [comment]
Yes that part only affects Overscan hidden.

**Comment by James-F2** [comment]
I've tried 4, 5 and 6 in all modes with "Hidden" option,, mainly with 240+24 (standard).
I agree 6 is the best option.

**Comment by sorgelig** [comment]
New release has been fine tuned using 240p Suite, so it dosplays the whole gred with single border lines on top and bottom. If it's not correct, then i suggest to notify the 240p Suite author first.

**Comment by paulb-nl** [comment]
I suggest to read my posts properly. The 240p suite defaults to start at line 22 to show 240 lines. You can also change to start at line 24 in the options menu which should show only 239 lines as described in the 240p test options help screen. 

With TOP_BL_LINES_E  18 the grid is properly centered for start line 24 which is what most games use.

**Comment by sorgelig** [comment]
so you suggest not so show top line in 240p Suite?

**Comment by paulb-nl** [comment]
For me with TOP_BL_LINES_E 18 all lines of the grid are visible at start line 22 or 24 when Overscan is set to Visible.

**Comment by sorgelig** [comment]
On CRT? 
on HDMI the top red line is not visible if TOP_BL_LINES_E 18

**Comment by sorgelig** [comment]
i see.. i've used v1.04

**Comment by sorgelig** [comment]
in 1.10 only 352x240 grid has good look with one border line on top and bottom. All other res have 2 border lines on bottom and non on top.

**Comment by James-F2** [comment]
Go to options and change start from row 24.

**Comment by paulb-nl** [comment]
That seems to be a bug with the 352x240 grid only. It always starts on line 24 even if line start is set to 22 in options.

**Comment by sorgelig** [comment]
Suite getting weird in 1.10.. It starts in mode not used in most games.. At least there is an option. 
More and more cryptic.

**Comment by ArtemioUrbina** [comment]
> 
> 
> That seems to be a bug with the 352x240 grid only. It always starts on line 24 even if line start is set to 22 in options.

I had to check since it was made so many years ago, but checking on hardware I do get changes. 

When using the default start at line 22, I get the full grid (showing a Duo R, conencted to a PVM via composite and to a scope showing the starting line)

![IMG_20200520_001752_HDR](https://user-images.githubusercontent.com/6305986/82408293-edfb5280-9a30-11ea-8b4a-d5d9fc1266b8.jpg)

Here is the capture form the scope when using line 22:
![Line22](https://user-images.githubusercontent.com/6305986/82408360-09fef400-9a31-11ea-96e4-570586af9365.png)
And a close up
![Line22-grid](https://user-images.githubusercontent.com/6305986/82408371-0ec3a800-9a31-11ea-81b4-32a8923b9772.jpg)

And here is the scope with line 24 set under options:
![Line24](https://user-images.githubusercontent.com/6305986/82408434-2dc23a00-9a31-11ea-8c99-8615dc5ea696.png)

And the grid on the PVM:
![Line24-grid](https://user-images.githubusercontent.com/6305986/82408605-8db8e080-9a31-11ea-8410-42faf7596dd9.jpg)


Here are the captures from MiSTerRGBS output. This first one has the scope set to the same trigger and position on Channel 1 while using Sync. Channel 2 has the Red signal, and it can be appreciated that the grid does not start at the same line as in the Duo above

![Mister-Line22-same-hw](https://user-images.githubusercontent.com/6305986/82409603-c2c63280-9a33-11ea-93a0-ea5431c79c9a.png)

Here is the same capture zoomed out while the cursors retain the Duo timming but showing the start line for the MiSTer

![Mister-Line22-zoom-out](https://user-images.githubusercontent.com/6305986/82409697-e7baa580-9a33-11ea-9b24-b20a158be58f.png)

I know my labeling might be confusing in the suite, any suggestions are more than welcome.

**Comment by sorgelig** [comment]
Did you set option Overscan = Enabled? 
From oscilloscope it looks like overscan is disabled.

**Comment by paulb-nl** [comment]
Hi Artemio. Thanks for your testing!

I see on the PVM that you used the 320 grid. Did you also try the 352 grid? It seems to start at the same line regardless of start line 22 or 24. It also does not have the 224p version.

**Comment by ArtemioUrbina** [comment]
> 
> 
> Did you set option Overscan = Enabled?
> From oscilloscope it looks like overscan is disabled.

You are right, I had overscan disabled. Thank you.

I repeated the tests with overscan enabled, and the difference seems to be only one line.

Duo Line 22
![Duo-Line22](https://user-images.githubusercontent.com/6305986/82468737-c89a3300-9a88-11ea-9163-c9579a90c635.png)

Mister Line 22
![Mister-Line22-Overscan](https://user-images.githubusercontent.com/6305986/82468752-cd5ee700-9a88-11ea-95ab-751ff80a1a02.png)

Duo Line 24
![Duo-Line24](https://user-images.githubusercontent.com/6305986/82468774-d2239b00-9a88-11ea-9220-cbc1053578ac.png)

Mister Line 24
![Mister-Line24-Overscan](https://user-images.githubusercontent.com/6305986/82468788-d64fb880-9a88-11ea-88bf-ba808672a8c8.png)

**Comment by ArtemioUrbina** [comment]
> 
> 
> Hi Artemio. Thanks for your testing!
> 
> I see on the PVM that you used the 320 grid. Did you also try the 352 grid? It seems to start at the same line regardless of start line 22 or 24. It also does not have the 224p version.

No, thank you guys for the amazing work!

I didn't try the 352 grid. It was originally intended just to help in adjustments for R-Type.

And you are right it is inconsistent because of that. I am fixing it now thanks to this. It now respects line 22 and 24 option. And I'll look into adding a 224 version.

**Comment by sorgelig** [comment]
Well, i've adjusted only the vblank against VDC output.
I will check VSync. It affects the other modules such as VDC, so it's not just simple change of the number.

**Comment by mjj03301977** [comment]
Thank you all for trying to make this perfect! Much appreciated! :)

**Comment by ArtemioUrbina** [comment]
> 
> 
> Hi Artemio. Thanks for your testing!
> 
> I see on the PVM that you used the 320 grid. Did you also try the 352 grid? It seems to start at the same line regardless of start line 22 or 24. It also does not have the 224p version.

I attach the release candidate version of the suite that includes these changes, and a few more I still need to test under linearity.

[240pSuite_1.11rc_SuperCDROM.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/4658493/240pSuite_1.11rc_SuperCDROM.zip)

**Comment by James-F2** [comment]
Looks like 352 grid is fixed.
In the Overscan test pattern the Bottom while line starts one line above the grey background in 240+24 mode, needs to be fixed too.

**Comment by ArtemioUrbina** [comment]
> 
> 
> Looks like 352 grid is fixed.
> In the Overscan test pattern the Bottom white line starts one line above the grey background in 240+24 mode, needs to be fixed too.

Looked into it, and here are the results. 

240p+22 overscan all in grey :
![240-22line-overscan](https://user-images.githubusercontent.com/6305986/82619108-a42e7b80-9b9a-11ea-8044-4202bf22f5a3.png)

240p+22 overscan, top and bottom white lines active:
![240-22line-overscan-top-bottom](https://user-images.githubusercontent.com/6305986/82619132-b9a3a580-9b9a-11ea-9d47-ca2d0ad59cad.png)

240p+24 overscan all in grey :
![240-24line-overscan](https://user-images.githubusercontent.com/6305986/82619145-c1634a00-9b9a-11ea-954c-6c552393cd14.png)

240p+24 overscan, top and bottom white lines active:
![240-24line-overscan-top-bottom](https://user-images.githubusercontent.com/6305986/82619159-c7f1c180-9b9a-11ea-935d-a96785eb6460.png)

Just as reference:
![top-bottom-active](https://user-images.githubusercontent.com/6305986/82619231-fe2f4100-9b9a-11ea-8048-ec8432ea56e2.jpg)

I verified this visually in a PVM-20M2MDU before checking with the scope, but wanted to be absolutely sure of it.

As you can see, the white lines start at the last line where the grey is drawn

Please let me know if I can help in any way.




--

**Comment by James-F2** [comment]
![20200522_094036](https://user-images.githubusercontent.com/31185814/82638982-7dab2780-9c10-11ea-8019-3f088ec4ede9.jpg)

**Comment by ArtemioUrbina** [comment]
> 
> 
> HDMI 240p+24:
> ![20200522_094036](https://user-images.githubusercontent.com/31185814/82638982-7dab2780-9c10-11ea-8019-3f088ec4ede9.jpg)

On which model? Maybe it varies, I have almost all models and can confirm it. The Duo R didn't present it like such. Here it is with line 24 enabled.

![DSC_0088](https://user-images.githubusercontent.com/6305986/82639888-3d778500-9bcf-11ea-8f63-7965983bb9f5.JPG)

As you can see from the above oscilloscope captures, the PCE can't draw line 240 when starting from line 24.

**Comment by James-F2** [comment]
Sorry, I should have clarified.
This is on MiSTer (HDMI output 240p+24) with the 1.11rc posted  above.

**Comment by ArtemioUrbina** [comment]
> 
> 
> Sorry, I should have clarified.
> This is on MiSTer (HDMI output 240p+24) with the 1.11rc posted above.

Ah I see. I understand now. 

It is true, internally the suite does exactly what you describe, but the result you are showing is never achieved on any PCE or TG16, since they can't draw like 240 when starting from line 24.

It is coded as such because tiles are 8 pixels tall, and I would need to either draw a black line at the last line, or have a 7 grey 1 black tile for the bottom row.

I can draw the black line on top of it, but since the hw can't show the line, I saw no purpose.

I am guessing that under this circumstances, the grid is also fully drawn instead of cutting the last red line.

**Comment by paulb-nl** [comment]
Clipping the last lines properly is not implemented yet. The question is does the 6270 not output the last lines when it goes beyond the max fixed active area (more VRAM access time) or does the 6260 just hide the lines.

**Comment by sorgelig** [comment]
> Duo Line 24
> ![Duo-Line24](https://user-images.githubusercontent.com/6305986/82468774-d2239b00-9a88-11ea-9220-cbc1053578ac.png)
> 
> Mister Line 24
> ![Mister-Line24-Overscan](https://user-images.githubusercontent.com/6305986/82468788-d64fb880-9a88-11ea-88bf-ba808672a8c8.png)

[TurboGrafx16.zip](https://github.com/MiSTer-devel/TurboGrafx16_MiSTer/files/4667008/TurboGrafx16.zip)
Test this version. It has adjusted vsync and accompanied vblank.

**Comment by ArtemioUrbina** [comment]
> 
> Test this version. It has adjusted vsync and accompanied vblank.

Here are the results:
Duo 240p+22
![line22Duo](https://user-images.githubusercontent.com/6305986/82712168-13fd3e80-9c4d-11ea-895c-94d09be48f8f.png)

Mister 240p+22
![line22Mister](https://user-images.githubusercontent.com/6305986/82712187-1b244c80-9c4d-11ea-8587-d724812d3bdd.png)

Duo 240p+24
![line24Duo](https://user-images.githubusercontent.com/6305986/82712206-21b2c400-9c4d-11ea-820a-550d2936283b.png)

Mister 240p+24
![line24Mister](https://user-images.githubusercontent.com/6305986/82712229-31320d00-9c4d-11ea-97c4-bfad0543f0d1.png)

**Comment by mjj03301977** [comment]
So when I check now with the latest build posted above and the latest beta 240p test suite, the gray border it cutoff at the top of grid tests using the default 22. When using 24, it looks good. Is this what you guys are seeing? Is that correct?

**Comment by sorgelig** [comment]
@ArtemioUrbina 
so, now vertical positions from MiSTer now matches the real HW?

**Comment by ArtemioUrbina** [comment]
@sorgelig Yes that is right, MiSTer matches HW on vertical positions.

**Comment by sorgelig** [comment]
Fixed
